<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CAPHYD-LAP-081" ignored="0" name="Default test" tests="6" failures="1" timestamp="15 Sep 2019 17:38:47 GMT" time="0.072" errors="0">
  <testcase name="Registration" time="0.014" classname="TestNG.FinalCode_TestNG.testAnotations">
    <failure type="java.lang.AssertionError" message="Registration faailed">
      <![CDATA[java.lang.AssertionError: Registration faailed
at org.testng.Assert.fail(Assert.java:96)
at TestNG.FinalCode_TestNG.testAnotations.Registration(testAnotations.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Registration -->
  <testcase name="Login" time="0.003" classname="TestNG.FinalCode_TestNG.testAnotations"/>
  <testcase name="AddProdcutToCart" time="0.001" classname="TestNG.FinalCode_TestNG.testAnotations"/>
  <testcase name="CheckoutJourney" time="0.001" classname="TestNG.FinalCode_TestNG.testAnotations"/>
  <testcase name="PaceOrder" time="0.002" classname="TestNG.FinalCode_TestNG.testAnotations"/>
  <testcase name="Logout" time="0.006" classname="TestNG.FinalCode_TestNG.testAnotations"/>
</testsuite> <!-- Default test -->
